version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=cedric_admin
      - POSTGRES_PASSWORD=admin_cedric
      - POSTGRES_DB=MesActions
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
